[General]
discordUrl=https://discord.gg/yxkVn4wBad

# 安卓版：首次启动从 CDN 自动加载资源，之后使用本地缓存
autoLoadGameRes=yes
gameresBaseUrl=//stdres.wangerhuoda.cn/
gameresBaseUrls=//wyhjres2.bun.sh.cn/
mapsBaseUrl=//gmap.wangerhuoda.cn/map/
modsBaseUrl=//gmap.wangerhuoda.cn/mod/
musicBaseUrl=//stdres.wangerhuoda.cn/music/
gameResArchiveUrl=https://download.ra2web.com/full-pack.7z

# 安卓版配置
defaultFullyPackUrl=
patchNotesUrl=
ladderRulesUrl=//www.ra2web.com/ladder-rules.html
modSdkUrl=https://github.com/ra2web/mod-sdk
donateUrl="//ra2web.com/#donate"
victoryShopUrl=https://center.bun.sh.cn
breakingNewsUrl=./breaking-news.html
oldClientsBaseUrl=./old/
quickMatchEnabled=yes
botsEnabled=yes
debugLogging=wol
debugGameState=yes

# Chronodivide 中国大区专供
defaultLanguage=zh-CN
forcedModId=gonghui
viewport.width=1024
viewport.height=768

# P2P CDN
p2pCdnEnabled=yes
p2pCdnTrackerUrl=wss://gserv.gz.wangerhuoda.cn:38443/p2p-cdn
p2pCdnIceServers=stun:gserv.gz.wangerhuoda.cn:3478

[Sentry]
dsn=https://268e10e6b2c60224fa86d0910a033a6f@sentry.wangerhuoda.cn/1
env=production-android
defaultIntegrations=yes
autoSessionTracking=no

[CorsProxy]
archive.org="https://game.chronodivide.com/cors-proxy/?url="
